name: FoxKiller
description: Fun plugin
version: 1.2.0-1.21.3
api-version: 1.21.3
main: com.github.PatrykCholewa.FoxKiller.FoxKillerPlugin
bootstrapper: com.github.PatrykCholewa.FoxKiller.FoxKillerPluginBootstrap
